name: hello_world_app
description: A comprehensive Flutter application demonstrating SDK configuration
publish_to: 'none' # Remove this line if you want to publish to pub.dev

# The following line prevents the package from being accidentally published
version: 1.0.0+1

# SDK Configuration - Critical Section
environment:
  sdk: '>=3.4.4 <4.0.0'  # Dart SDK version constraint
  flutter: '^3.24.0'     # Flutter SDK version constraint

# Production Dependencies
dependencies:
  flutter:
    sdk: flutter

  # UI and Navigation
  cupertino_icons: ^1.0.6
  material_design_icons_flutter: ^7.0.7296

  # State Management
  provider: ^6.1.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6

  # Network and API
  http: ^1.2.1
  dio: ^5.4.3+1

  # Storage
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1

  # Utilities
  intl: ^0.19.0
  path_provider: ^2.1.3

# Development Dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting and Code Quality
  flutter_lints: ^4.0.0
  very_good_analysis: ^6.0.0

  # Testing
  mockito: ^5.4.4
  build_runner: ^2.4.12

  # Code Generation
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0

# Flutter Configuration
flutter:
  uses-material-design: true

  # Assets Configuration - Only include if you have these directories
  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/data/

  # Fonts Configuration - Only include if you have these font files
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700